system: Update kernel/wifi/misc
Changes:
-video: tegra-ics: backport/sync with nvidia's 3.1
-~100+ video changes from nvidia's android-nv-3.1/rel-15r7
-media: video: avp-ics: backport/sync with nvidia's 3.1
media: fix corner case in tegra_mediaserver
media: tegra: avp: set emc to max for video only
ARM: tegra: gart: Replace memory barrier with register read-back
ARM: tegra: gart: Fix wrong initialization order
video: tegra: add ioctl to query DC capabilities
media: tegra_camera: Enable Null sensor
net: wireless: bcmdhd: Skip inaccurate wl_construct_reginfo() call
net: wireless: bcmdhd: Add wiphyband update for country change
net: wireless: bcmdhd: Return wl_construct_reginfo() call
net: wireless: bcmdhd: Skip country setting if unnecessary
net: wireless: bcmdhd: Add mutex to wl_update_wiphybands()
net: wireless: bcmdhd: Init locks in dhd_attach() at the beginning
net: wireless: bcmdhd: Update wiphy bands on band change
net: wireless: bcmdhd: Fix P2P GO hang issue
net: wireless: bcmdhd: Remove country update from wl_update_wiphybands
net: wireless: bcmdhd: Add info_string param with driver/fw/chip info
net: wireless: bcmdhd: Adjust driver/fw/chip info format
net: wireless: bcmdhd: Use proper jiffie-related functions
net: wireless: bcmdhd: Prevent HT Avail request failure to flood the log
cpufreq: Allow adjust_jiffies for Tegra 2 SMP
Revert "cpufreq: patch to address issue with second core forgetting min/max clock frequency
cpufreq: do not forget min/max clock frequency on cpu hotplug
Added improved glibc memcpy and memmove functions.
kernel:mm: Backported vzalloc to support ZRAM
vmscan: change shrink_slab() interfaces by passing shrink_control
vmscan: change shrinker API by passing shrink_control struct
-defconfig: ics: regen
arm: mm: convert cpa_lock to mutex.
arm: mm: Optimze cache flush in CPA.
ARM: mm: Use CONFIG_CPA
ARM: mm: Add config flag for CPA.
ARM: tegra: Enable CPA.
-defconfig: ics: regen
mm: Ensure pte and pmd stores ordering.
-tegra: clocks: modify usbd shared clock mapping
usb: gadget: android: Don't allow changing the functions list if enabled
usb: gadget: android: dump the uevents sent when changing states
usb: gadget: android: always update the sw_connected state
usb: gadget: android: follow proper order on disconnect
usb: gadget: adb: Only enable the gadget when adbd is ready
-usb: gadget-ics: sleep after gadget disconnect for VARIATION_TEGRA
Add ACCESSORY_SET_AUDIO_MODE control request and ioctl
USB: gadget: f_accessory: Add support for HID input devices
USB: gadget: f_audio_source: New gadget driver for audio output
USB: gadget: f_audio_source: Adjust packet timing to reduce glitches
Revert "cpufreq: Allow adjust_jiffies for Tegra 2 SMP"
Revert "wireless: bcmdhd: remove __wl_band_5ghz_a.n/2ghz.n_channel in bandlist conditional
net: wireless: bcmdhd: Fill station_info packet fields
Revert "ARM: tegra: Enable CPA."
-defconfig: ics: unset CPA
cpufreq: interactive: take idle notifications only when active
USB: gadget: f_audio_source: Fix error handling and increase packet size
-defconfig: ics: set NVMAP_PAGE_POOLS, CPA and unset NVMAP_VPR
block: introduce the BFQ-v4 I/O sched for 2.6.38
-video: tegra-ics: remove *3dctx*
video: tegra: host: Fix error case memory leaks
video: tegra: host: Do not panic on hardware timeout
Revert "video: tegra: dc: remove bandwidth efficiency"
-defconfig: ics: reduce TEGRA_EMC_TO_DDR_CLOCK to 2
video: tegra-ics: dc: allow 6 underflows before reset
-cpufreq: interactive: return back to stock values
Revert "video: tegra: host: Fix error case memory leaks"
Revert "video: tegra: dc: add tracing information"
Revert "video: tegra3: dc: remove hard coded HDMI rates"
video: tegra: add TEGRA_HDMI_74MHZ_LIMIT to config for ICS
defconfig: ics: regen
Revert "video: tegra: host: Fix error case memory leaks"
Revert "video: tegra: dc: add tracing information"
Revert "video: tegra3: dc: remove hard coded HDMI rates"
video: tegra: add TEGRA_HDMI_74MHZ_LIMIT to config for ICS
-defconfig: ics: regen
kstrto*: converting strings to integers done (hopefully) right
time: Introduce get_monotonic_boottime and ktime_get_boottime
net: wireless: bcmdhd: Use correct time from boot for TSF
netfilter: xt_IDLETIMER: Rename INTERFACE to LABEL in netlink notification.
USB: gadget: f_audio_source: Fix use after free in audio_unbind
USB: gadget: f_audio_source: Fix compilation error
mmc: Make sure host is disabled on suspend

-Reference:
 github.com/hyperdroid, github.com/kcrudup, nv-tegra.nvidia.com
 android.googlesource.com, github.com/faux123, arcee, aosp.schiznik.net
 github.com/ezterry, github.com/arco

-Note:
 When HDMI is connected with the adapter, this is thrown:
 WARNING: at kernel/irq/manage.c:290 enable_irq+0x4c/0x74()
 Unbalanced enable for IRQ 106
  -To be investigated.

Change-Id: I8c0f21297260ec1493ec9e27894fd4b77c13f1d4